server:
  port: 8081

spring:
  redis:
    host: 192.168.0.172
    port: 6379
    password: yky
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
        max-idle: 8 # 连接池中的最大空闲连接
        max-wait: 1000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      shutdown-timeout: 100 # 关闭超时时间